language: go

os:
  - linux

go:
  - "1.13"

env:
  - GO111MODULE=on

install:
  - go mod vendor

script:
  - go fmt ./... && [[ -z `git status -s` ]]
  - go test ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
